plugins:
  retort_enabled:
    default: true
    client: true
  retort_disabled_emojis:
    type: emoji_list
    default: ""
    client: false
  retort_withdraw_tolerance:
    type: number
    default: 5
    client: false
  retort_allow_multiple_reactions:
    default: true
  retort_disabled_categories:
    type: category_list
    default: ""
    client: true
  retort_disabled_users:
    type: list
    default: ""
    client: false
  retort_max_per_day: 50
  retort_tl2_max_per_day_multiplier: 1.5
  retort_tl3_max_per_day_multiplier: 2
  retort_tl4_max_per_day_multiplier: 3
