plugins:
  retort_enabled:
    default: true
    client: true
  retort_allowed_emojis:
    type: emoji_list
    default: relaxed|laughing|+1|heart|rage|poop
    client: true
  retort_allow_multiple_reactions:
    default: true
  retort_disabled_categories:
    type: category_list
    default: ""
    client: true
  retort_max_per_day: 50
  retort_tl2_max_per_day_multiplier: 1.5
  retort_tl3_max_per_day_multiplier: 2
  retort_tl4_max_per_day_multiplier: 3
